version: '3.3'

services:
  app:
    build: ./
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_REDIS_HOST: redis
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.2
    restart: always
  redis:
    image: redis:6.0
    restart: always
#TODO remove mongo-express
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081