version: '3.3'

services:
#  app:
#    build: ./
#    restart: always
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATA_MONGODB_HOST: mongo
#      OMDB_APIKEY: "${OMDB_APIKEY}"
#    depends_on:
#      - mongo
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081