omdb:
  url: http://www.omdbapi.com
  apiKey: test-key

mongock:
  change-logs-scan-package:
    - com.example.cinema.db

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG